### ISSUE TITLE
deel-lip does not work with tf2.6

### ISSUE THREAD

**Issue by thib-s** [deel-ai/deel-lip#45] opened 2021-12-09 10:33 UTC
As `tf 2.6` does not include keras, import `tf.keras....` breaks. This is not the case with `tf 2.5` nor `tf 2.7`.

A quick fix is to remove support for 2.6. A better fix would be to re-route keras imports specifically for tf2.6

**Comment by cofri** [comment] 2021-12-21 09:35
The bug is present in Tensorflow versions 2.6.0 and 2.6.1 when using `keras==2.7.0`. It can be fixed by manually installing `keras==2.6.0` along with TF 2.6.0 or 2.6.1.
Tensorflow 2.6.2 works correctly, since it enforces Keras to be 2.6.0. For more information, see https://stackoverflow.com/a/69830680/17578620

Since it is not a bug related to deel-lip, but only related to TF/Keras, I think it's preferred not to change anything in deel-lip. However, if necessary, we could add a disclaimer to warn users that TF and Keras versions must match for 2.6.*.

**Closed** 2022-01-18 09:14 UTC
Labels: bug
